---
- name: Add Ansible PPA
  apt_repository:
    repo: ppa:ansible/ansible
    filename: ansible

- name: Update repositories cache
  apt:
    update_cache: yes
  changed_when: false

- name: Install Ansible
  apt:
    name: ansible
