---
- name: Add Docker APT key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg

- name: Install required packages for Docker
  apt:
    name: "{{ item }}"
  with_items:
    - apt-transport-https
    - python-docker
    - make
    - git

- name: Add Docker repository
  apt_repository:
    repo: "deb [arch={{ awx_arch }}] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    filename: docker
    update_cache: true

- name: Install Docker
  apt:
    name: docker-ce
